spring:
  application:
    name: grupo
  datasource:
    url: jdbc:postgresql://localhost:5432/banco_pubsub
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

app:
  pubsub:
    project-id: serjava-demo
    subscription-id: sub-grupo6
    credentials-path: ../key.json